--- 
- name: Deploying the application to the web server
  hosts: web
  vars:
    dockerImage: ravikharel/nginx
  tasks:
    - name: copy the tar image to the web server
      copy: 
        src: "{{ workspace }}/nginx:latest.tar"
        dest: /home/vagrant/
    - name: Loading the tar file in the remote server
      command: docker load -i /home/vagrant/nginx:latest.tar

    - name: Running the nginx container 
      command: docker run -d -p 82:80 --name nginxcontainer ${dockerImage}:${number}

