--- 
- name: Doing something.... 
  hosts: web
  tasks: 
    - name: Copying the file
      copy: 
        src: "{{ playbook_dir }}/2133_moso_interior/"
        dest: /var/www/html/*
      notify: Restart Nginx
  handlers: 
    - name: Restart nginx
      service: 
        state: restarted

