---
- name: Deploying the application to the web server
  hosts: web
  vars:
    dockerImage: "ravikharel/nginx"
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pulling the docker image to the web server
      command: "docker pull {{ dockerImage }}:{{ number }}"

    - name: Copying the file to the web server
      copy:
        src: "{{ workspace }}/docker-compose.yml"
        dest: /home/vagrant/

    - name: Running the docker compose file
      community.docker.docker_compose:
        project_src: /home/vagrant/
        env:
          imageName: "{{ dockerImage }}"
          number: "{{ number }}"