---
- name: Doing something....
  hosts: web
  tasks:
    - name: Copying the file
      copy:
        src: "{{ workspace }}/2133_moso_interior/"
        dest: /var/www/html/
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

